interface Env { DB: D1Database }

type Page = { id:string; slug:string; store_name:string; description:string; whatsapp_number:string; plan:string; published:number; branding_hidden:number; created_at:string; updated_at:string };
type Product = { id:string; page_id:string; name:string; price:string; description:string; image_url:string; whatsapp_message:string; sort_order:number };

const esc = (v: unknown) => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!));
const json = (data: unknown, status = 200) => new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8' } });
const slugify = (v: string) => v.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || crypto.randomUUID().slice(0, 8);
const cleanPhone = (v: string) => v.replace(/[^0-9]/g, '');
const now = () => new Date().toISOString();

function layout(title: string, body: string) {
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>
  *{box-sizing:border-box} body{font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0;background:#fff;color:#000} a{color:#000} .wrap{max-width:1080px;margin:0 auto;padding:24px}.nav{border-bottom:2px solid #000}.nav .wrap{display:flex;justify-content:space-between;gap:16px;align-items:center}.brand{font-weight:900;letter-spacing:-.04em;font-size:28px;text-decoration:none}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.hero{padding:56px 0;border-bottom:2px solid #000}.hero h1{font-size:clamp(44px,8vw,92px);line-height:.88;letter-spacing:-.08em;margin:0 0 18px}.lead{font-size:22px;max-width:680px}.card,.panel,form{border:2px solid #000;padding:18px;background:#fff}.btn,button,input,textarea,select{font:inherit}.btn,button{display:inline-block;border:2px solid #000;background:#000;color:#fff;padding:12px 16px;text-decoration:none;font-weight:800;cursor:pointer}.btn.alt,button.alt{background:#fff;color:#000} input,textarea,select{width:100%;border:2px solid #000;padding:11px;margin:6px 0 14px;background:#fff;color:#000} label{font-weight:800}.muted{color:#444}.row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.pill{border:2px solid #000;padding:5px 8px;font-weight:800}.product{display:grid;grid-template-columns:84px 1fr;gap:12px}.ph{width:84px;height:84px;border:2px dashed #000;display:grid;place-items:center;font-size:12px}.price{font-weight:900;font-size:22px}.danger{border-color:#000;background:repeating-linear-gradient(45deg,#fff,#fff 8px,#eee 8px,#eee 16px)}.footer{border-top:2px solid #000;margin-top:40px}.small{font-size:13px}.qr{width:144px;height:144px;border:2px solid #000;background:linear-gradient(90deg,#000 10px,transparent 10px) 0 0/24px 24px,linear-gradient(#000 10px,transparent 10px) 0 0/24px 24px}.right{margin-left:auto}@media(max-width:640px){.product{grid-template-columns:1fr}.ph{width:100%;height:140px}.hero{padding:32px 0}}
  </style></head><body><nav class="nav"><div class="wrap"><a class="brand" href="/">zippp.link</a><div class="row"><a href="/app">App</a><a href="/pricing">Pricing</a></div></div></nav>${body}<footer class="footer"><div class="wrap small">zippp.link — WhatsApp-first sales pages for small sellers.</div></footer></body></html>`, { headers: { 'content-type': 'text/html; charset=utf-8' } });
}

async function landing() { return layout('zippp.link — WhatsApp sales pages', `<main><section class="hero"><div class="wrap"><p class="pill">Black & white MVP</p><h1>Create a WhatsApp sales page in 5 minutes.</h1><p class="lead">Show products, prices, and one-tap WhatsApp buttons from one simple link and QR-ready page.</p><div class="row"><a class="btn" href="/app">Create free page</a><a class="btn alt" href="/demo">View demo</a></div></div></section><section class="wrap grid"><div class="card"><h2>Built for sellers</h2><p>Not a creator link directory. It is a sales page made for chat-based closing.</p></div><div class="card"><h2>Product → price → chat</h2><p>Cards keep buyer questions short and start the right WhatsApp conversation.</p></div><div class="card"><h2>Bio, counter, flyer</h2><p>Use one link and one QR for Instagram, packaging, menus, and local outreach.</p></div></section><section class="wrap"><h2>Plans</h2><div class="grid"><div class="card"><h3>Free</h3><p class="price">$0</p><p>1 page, 6 products, zippp.link branding.</p></div><div class="card"><h3>Starter</h3><p class="price">$9/year</p><p>30 products, remove branding, views + WhatsApp click analytics.</p></div><div class="card"><h3>Pro</h3><p class="price">$19/year</p><p>Manual activation for up to 3 pages and advanced QR variants.</p></div></div></section></main>`); }

async function ensureDemo(env: Env) {
  const found = await env.DB.prepare('SELECT id FROM pages WHERE slug = ?').bind('demo').first<Page>();
  if (found) return;
  const id = crypto.randomUUID();
  await env.DB.prepare('INSERT INTO pages (id, slug, store_name, description, whatsapp_number, plan, published) VALUES (?, ?, ?, ?, ?, ?, 1)').bind(id, 'demo', 'Demo Coffee Stall', 'A tiny sample page for local sellers who close orders in WhatsApp.', '15551234567', 'free').run();
  for (const [i,p] of [['Iced Latte','$4','Cold latte, ready for pickup.'],['Banana Bread','$3','Fresh slice, limited daily batch.'],['Combo','$6','Coffee plus banana bread.']].entries()) await env.DB.prepare('INSERT INTO products (id,page_id,name,price,description,sort_order) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(), id, p[0], p[1], p[2], i).run();
}

async function app(env: Env) {
  const pages = await env.DB.prepare(`SELECT p.*, COALESCE(SUM(CASE WHEN e.event_type='view' THEN 1 ELSE 0 END),0) views, COALESCE(SUM(CASE WHEN e.event_type='whatsapp_click' THEN 1 ELSE 0 END),0) clicks FROM pages p LEFT JOIN analytics_events e ON e.page_id=p.id GROUP BY p.id ORDER BY p.updated_at DESC`).all<Page & {views:number;clicks:number}>();
  const list = pages.results.map(p => `<div class="card"><div class="row"><h3>${esc(p.store_name)}</h3><span class="pill">${esc(p.plan)}</span></div><p><a href="/${esc(p.slug)}">/${esc(p.slug)}</a></p><p>${esc(p.description)}</p><p class="small">Views: ${p.views} · WhatsApp clicks: ${p.clicks}</p><div class="row"><a class="btn" href="/app/page/${p.id}">Edit</a><a class="btn alt" href="/${esc(p.slug)}">Public</a></div></div>`).join('') || '<p>No pages yet. Create one below.</p>';
  return layout('zippp.link app', `<main class="wrap"><h1>Dashboard</h1><p class="lead">No auth MVP: create and manage public WhatsApp sales pages directly.</p><div class="grid"><section class="panel"><h2>Create page</h2><form method="post" action="/api/pages"><label>Store name</label><input required name="store_name" placeholder="Adit Coffee"><label>Slug</label><input name="slug" placeholder="adit-coffee"><label>WhatsApp number</label><input required name="whatsapp_number" placeholder="15551234567"><label>Description</label><textarea name="description" placeholder="What do you sell?"></textarea><button>Create free page</button></form></section><section><h2>Your pages</h2>${list}</section></div></main>`); }

async function editPage(env: Env, id: string) {
  const page = await env.DB.prepare('SELECT * FROM pages WHERE id=?').bind(id).first<Page>();
  if (!page) return layout('Not found', '<main class="wrap"><h1>Page not found</h1></main>');
  const products = await env.DB.prepare('SELECT * FROM products WHERE page_id=? ORDER BY sort_order, created_at').bind(id).all<Product>();
  const limit = page.plan === 'free' ? 6 : page.plan === 'starter' ? 30 : 100;
  const productList = products.results.map(p => `<div class="card product"><div class="ph">PHOTO</div><div><h3>${esc(p.name)}</h3><p class="price">${esc(p.price)}</p><p>${esc(p.description)}</p><form method="post" action="/api/products/${p.id}/delete"><button class="alt">Delete</button></form></div></div>`).join('');
  return layout(`Edit ${page.store_name}`, `<main class="wrap"><div class="row"><h1>Edit ${esc(page.store_name)}</h1><a class="btn alt right" href="/${esc(page.slug)}">View public</a></div><div class="grid"><section class="panel"><h2>Page details</h2><form method="post" action="/api/pages/${page.id}"><label>Store name</label><input name="store_name" value="${esc(page.store_name)}"><label>Slug</label><input name="slug" value="${esc(page.slug)}"><label>WhatsApp number</label><input name="whatsapp_number" value="${esc(page.whatsapp_number)}"><label>Description</label><textarea name="description">${esc(page.description)}</textarea><label>Plan</label><select name="plan"><option ${page.plan==='free'?'selected':''}>free</option><option ${page.plan==='starter'?'selected':''}>starter</option><option ${page.plan==='pro'?'selected':''}>pro</option></select><button>Save page</button></form></section><section class="panel"><h2>Add product</h2><p class="small">${products.results.length}/${limit} products used.</p><form method="post" action="/api/pages/${page.id}/products"><label>Name</label><input required name="name"><label>Price</label><input name="price" placeholder="$9"><label>Description</label><textarea name="description"></textarea><label>Image URL</label><input name="image_url" placeholder="https://..."><label>Custom WhatsApp message</label><textarea name="whatsapp_message"></textarea><button ${products.results.length>=limit?'disabled':''}>Add product</button></form></section></div><h2>Products</h2><div class="grid">${productList || '<p>No products yet.</p>'}</div><section class="panel"><h2>Share</h2><p><input readonly value="${esc(new URL('/'+page.slug, 'https://zippp.link').toString())}"></p><div class="qr" title="QR placeholder"></div><p class="small">QR-ready placeholder. Use browser/share tools for this low-fidelity MVP.</p></section></main>`);
}

async function publicPage(env: Env, slug: string, req: Request) {
  if (slug === 'demo') await ensureDemo(env);
  const page = await env.DB.prepare('SELECT * FROM pages WHERE slug=? AND published=1').bind(slug).first<Page>();
  if (!page) return new Response('Not found', { status: 404 });
  await env.DB.prepare('INSERT INTO analytics_events (id,page_id,event_type,source) VALUES (?,?,?,?)').bind(crypto.randomUUID(), page.id, 'view', new URL(req.url).searchParams.get('src') || '').run();
  const products = await env.DB.prepare('SELECT * FROM products WHERE page_id=? ORDER BY sort_order, created_at').bind(page.id).all<Product>();
  const cards = products.results.map(p => { const text = p.whatsapp_message || `Hi ${page.store_name}, I want to ask about ${p.name} (${p.price}).`; const wa = `/go/${page.slug}/${p.id}?text=${encodeURIComponent(text)}`; return `<div class="card product">${p.image_url ? `<img class="ph" src="${esc(p.image_url)}" alt="${esc(p.name)}">` : '<div class="ph">PHOTO</div>'}<div><h2>${esc(p.name)}</h2><p class="price">${esc(p.price)}</p><p>${esc(p.description)}</p><a class="btn" href="${wa}">Chat on WhatsApp</a></div></div>`; }).join('');
  return layout(page.store_name, `<main><section class="hero"><div class="wrap"><p class="pill">WhatsApp sales page</p><h1>${esc(page.store_name)}</h1><p class="lead">${esc(page.description)}</p><a class="btn" href="/go/${page.slug}/store?text=${encodeURIComponent(`Hi ${page.store_name}, I saw your zippp.link page.`)}">Message on WhatsApp</a></div></section><section class="wrap"><h2>Products</h2><div class="grid">${cards || '<p>No products listed yet.</p>'}</div></section>${page.branding_hidden ? '' : '<section class="wrap small muted">Made with zippp.link</section>'}</main>`);
}

async function readForm(req: Request) { const fd = await req.formData(); return Object.fromEntries([...fd].map(([k,v]) => [k, String(v)])); }
const redirect = (to: string) => new Response(null, { status: 303, headers: { location: to } });

export default { async fetch(req: Request, env: Env): Promise<Response> { try {
  const url = new URL(req.url); const path = url.pathname;
  if (path === '/') return landing();
  if (path === '/pricing') return landing();
  if (path === '/app') return app(env);
  if (path.startsWith('/app/page/')) return editPage(env, path.split('/').pop()!);
  if (path === '/api/pages' && req.method === 'POST') { const f = await readForm(req); const id = crypto.randomUUID(); const slug = slugify(f.slug || f.store_name); await env.DB.prepare('INSERT INTO pages (id,slug,store_name,description,whatsapp_number,plan,published,updated_at) VALUES (?,?,?,?,?,?,1,?)').bind(id, slug, f.store_name || 'Untitled Store', f.description || '', cleanPhone(f.whatsapp_number || ''), 'free', now()).run(); return redirect(`/app/page/${id}`); }
  if (path.match(/^\/api\/pages\/[^/]+$/) && req.method === 'POST') { const id = path.split('/')[3]; const f = await readForm(req); const plan = ['free','starter','pro'].includes(f.plan) ? f.plan : 'free'; await env.DB.prepare('UPDATE pages SET slug=?,store_name=?,description=?,whatsapp_number=?,plan=?,branding_hidden=?,updated_at=? WHERE id=?').bind(slugify(f.slug), f.store_name, f.description || '', cleanPhone(f.whatsapp_number || ''), plan, plan === 'free' ? 0 : 1, now(), id).run(); return redirect(`/app/page/${id}`); }
  if (path.match(/^\/api\/pages\/[^/]+\/products$/) && req.method === 'POST') { const id = path.split('/')[3]; const page = await env.DB.prepare('SELECT plan FROM pages WHERE id=?').bind(id).first<{plan:string}>(); if (!page) return json({ error:'Page not found' },404); const count = await env.DB.prepare('SELECT COUNT(*) count FROM products WHERE page_id=?').bind(id).first<{count:number}>(); const limit = page.plan === 'free' ? 6 : page.plan === 'starter' ? 30 : 100; if ((count?.count || 0) >= limit) return json({ error:'Product limit reached' },400); const f = await readForm(req); await env.DB.prepare('INSERT INTO products (id,page_id,name,price,description,image_url,whatsapp_message,sort_order) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(), id, f.name, f.price || '', f.description || '', f.image_url || '', f.whatsapp_message || '', count?.count || 0).run(); return redirect(`/app/page/${id}`); }
  if (path.match(/^\/api\/products\/[^/]+\/delete$/) && req.method === 'POST') { const pid = path.split('/')[3]; const p = await env.DB.prepare('SELECT page_id FROM products WHERE id=?').bind(pid).first<{page_id:string}>(); await env.DB.prepare('DELETE FROM products WHERE id=?').bind(pid).run(); return redirect(`/app/page/${p?.page_id || ''}`); }
  if (path.startsWith('/go/')) { const [, , slug, productId] = path.split('/'); const page = await env.DB.prepare('SELECT * FROM pages WHERE slug=?').bind(slug).first<Page>(); if (!page) return new Response('Not found',{status:404}); await env.DB.prepare('INSERT INTO analytics_events (id,page_id,event_type,source) VALUES (?,?,?,?)').bind(crypto.randomUUID(), page.id, 'whatsapp_click', productId || '').run(); const text = url.searchParams.get('text') || `Hi ${page.store_name}`; return redirect(`https://wa.me/${page.whatsapp_number}?text=${encodeURIComponent(text)}`); }
  return publicPage(env, path.slice(1), req);
} catch (err) { return layout('Error', `<main class="wrap"><h1>Something broke</h1><pre>${esc(err instanceof Error ? err.message : String(err))}</pre><p><a href="/app">Back to app</a></p></main>`); } } };
